### ISSUE TITLE
Add @sqaunderhood

### ISSUE THREAD

**Issue by sudodoki** [iamstarkov/awesome-collective-twitters#17]
@sqaunderhood https://twitter.com/sqaunderhood?s=09
Would do it myself, unless I was away from computer

**Comment by iamstarkov** [comment]
do you know when it has been launched?

**Comment by sudodoki** [comment]
Seems like July 18

**Comment by iamstarkov** [comment]
July 14, though yes they started 18

**Comment by iamstarkov** [comment]
It is dead
