### ISSUE TITLE
AwesomeUnderhood

### ISSUE THREAD

**Issue by ilyashubin** [iamstarkov/awesome-collective-twitters#5]
Классный проект. Я подсел :+1: 
Очень много новой информации, полезных ссылок, ресурсов и т.д.
Но есть одна проблемка у этого формата: если пропустил пару дней или неделю, считай информация потеряна (листать лень ;D)
Поэтому я решил запилить небольшой агрегатор самых полезных андерхуд постов: http://ilyashubin.github.io/AwesomeUnderhood/
Надеюсь, кому-то кроме меня пригодится.

**Comment by davydovanton** [comment]
Выглядит круто, спасибо! Но я бы ещё rubyunderhood добавил бы :)

**Comment by iamstarkov** [comment]
если лень скроллить, то почему не будет лень скроллить бесконечный скроллинг?

**Comment by ilyashubin** [comment]
@davydovanton окей, добавлю рубиста!
@iamstarkov потому что во-первых тут вся инфа уже "отфильтрована" - сообщество проголосовало за самые крутые ништяки. Во-вторых, сортировка за неделю - пропустил неделю, например, и быстренько посмотрел, что пропустил из интересного. Без нужды листать кучу реплаев, ответов и т.д. Можешь считать это своеобразным дополнением для ленивых и тех, кто не смог присутствовать. Общения с авторами это, конечно, не заменит ;D

**Comment by davydovanton** [comment]
А ты выбираешь по кол-ву звёзд и ретвитов же?

**Comment by iamstarkov** [comment]
https://github.com/iamstarkov/jsunderhood/blob/master/dump/23ydobemos-tweets.json#L7-L25

**Comment by ilyashubin** [comment]
@davydovanton да, можно ленту отсортировать по кол-ву лайков/ретвитов. У api твиттера свои заморочки, так что все это берется только из последних 3200 твитов аккаунта.
Кстати, забыл ссылку на репо дать: https://github.com/ilyashubin/AwesomeUnderhood

**Comment by iamstarkov** [comment]
@ilyashubin вся информация есть в дампах аккаунтов и это всё можно сделать в рамках сайта. интересно?

**Comment by iamstarkov** [comment]
посмотри на мои пред сообщения

**Comment by ilyashubin** [comment]
@iamstarkov дампы есть для всех аккаунтов и авторов? Конечно интересно. Можно было бы сделать Hall of Fame сообщений за все существование ресура.
Правда, сейчас у меня с временем туго (сессия ;D), так что в ближайшее время максимум рубиста добавлю

**Comment by iamstarkov** [comment]
hall of fame не решит проблемы пропуска пары дней или недели. а если сделать на странице архива автора кнопку показать самое главное, то это как раз решит твою проблему

**Comment by iamstarkov** [comment]
закрою пока, так как проект заглох

**Comment by davydovanton** [comment]
Обидно, крутая идея была :(

**Comment by iamstarkov** [comment]
такое бывает с проектами

**Comment by iamstarkov** [comment]
насчёт самой идеи можно сделать такое же для каждого из проектов
